### ISSUE TITLE
Bootstrap 4 checkbox and radio buttons

### ISSUE THREAD

**Issue by ddomingos** [edx/paragon#58]
In the Bootstrap 4 theme, the active/checked state for checkbox and radio buttons has the same highlight that is used to indicate focus state. See the documentation example here:
https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons

The problem is that when tabbing through a page if a checkbox/radio is already selected there is no visual indicator that the element has been focused upon. As a keyboard navigating user, I can't tell that I am interacting with the checkbox or radio group if it is already selected.

In order to fix this, I would recommend removing the focus highlight from the active state and adding it back only when focused.

Example:
```css
/* Labels receive .focus and .active classes via the Bootstrap JS */

.btn:not([disabled]):not(.disabled).active,
.btn:not([disabled]):not(.disabled):active {
    box-shadow: none;
}
.btn.focus,
.btn:focus,
.btn.focus:not([disabled]):not(.disabled).active,
.btn.focus:not([disabled]):not(.disabled):active,
.btn:not([disabled]):not(.disabled).active:focus,
.btn:not([disabled]):not(.disabled):active:focus {
  /* Bootstrap uses different focus color for each button style. This example doesn't for simplicity */
  box-shadow: 0 0 0 0.2rem rgba(0,123,255,.5)
}
```
