### ISSUE TITLE
Bootstrap 4 responsive dropdowns

### ISSUE THREAD

**Issue by ddomingos** [edx/paragon#75]
Dropdown menus in Bootstrap 4 have `white-space: nowrap` set for each dropdown list item. On smaller screens, this causes longer list items to overflow the window, forcing horizontal scrollbars to appear.

Before:
![01_bs4-dropdown-before](https://user-images.githubusercontent.com/363443/32955880-3e097612-cb85-11e7-8c95-de0253e897fc.png)

In order to fix this, we can use the following CSS:
```css
.dropdown-menu {
    /* Set dropdown menu container to 100% of the viewport width minus 0.625rem  (≈5px). */
    max-width: calc(100vw - 0.625rem);
}
.dropdown-item {
    /* Truncate long menu items with an ellipsis. */
    text-overflow: ellipsis;
    overflow: hidden;
}
```
This snippet adds truncates long menu items and adds an ellipsis (…).

After:
![02_bs4-dropdown-after](https://user-images.githubusercontent.com/363443/32955881-3e3e53aa-cb85-11e7-801a-1d05dfde9569.png)

Viewport Units are supported in all current browsers except Opera Mini. **However**, "Chrome does not support viewport units…in calc() until version 34." [More info from caniuse.com](https://caniuse.com/#feat=viewport-units)

Calc is supported in all current browsers except Opera Mini. **However**, "Safari & iOS Safari (both 6 and 7) does not support viewport units (vw, vh, etc) in calc()." [More info from caniuse.com](https://caniuse.com/#feat=calc)
